name: first_aid_health_care
description: "A first aid and healthcare app with emergency features"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # Firebase packages
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

  # State management
  provider: ^6.1.4

  # Location and maps
  google_maps_flutter: ^2.12.0
  location: ^8.0.0
  geolocator: ^13.0.3
  geocoding: ^3.0.0
  flutter_map_marker_cluster: ^1.3.1

  # Offline storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # UI components
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  video_player: ^2.9.5
  chewie: ^1.11.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1

  # Utilities
  intl: ^0.20.2
  connectivity_plus: ^6.1.3
  permission_handler: ^11.4.0
  uuid: ^4.5.1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/data/
