// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1bNSM9ceG7zCs9AFPplWYCVyfdpJao7c',
    appId: '1:735064828729:web:e6a41a2ef1beb1dfd316e8',
    messagingSenderId: '735064828729',
    projectId: 'first-aid-health-care',
    authDomain: 'first-aid-health-care.firebaseapp.com',
    storageBucket: 'first-aid-health-care.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzJjJFzH39J2DQ-EbqLSJeDdwPGC_Zzqg',
    appId: '1:735064828729:android:c3252ca633567939d316e8',
    messagingSenderId: '735064828729',
    projectId: 'first-aid-health-care',
    storageBucket: 'first-aid-health-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs3mU83gIILomMCwgdG5xL9QJAJSTV4Rc',
    appId: '1:735064828729:ios:0950fe64d4f9fff7d316e8',
    messagingSenderId: '735064828729',
    projectId: 'first-aid-health-care',
    storageBucket: 'first-aid-health-care.firebasestorage.app',
    iosBundleId: 'com.example.firstAidHealthCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs3mU83gIILomMCwgdG5xL9QJAJSTV4Rc',
    appId: '1:735064828729:ios:0950fe64d4f9fff7d316e8',
    messagingSenderId: '735064828729',
    projectId: 'first-aid-health-care',
    storageBucket: 'first-aid-health-care.firebasestorage.app',
    iosBundleId: 'com.example.firstAidHealthCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1bNSM9ceG7zCs9AFPplWYCVyfdpJao7c',
    appId: '1:735064828729:web:b6f2952bcdcc8a77d316e8',
    messagingSenderId: '735064828729',
    projectId: 'first-aid-health-care',
    authDomain: 'first-aid-health-care.firebaseapp.com',
    storageBucket: 'first-aid-health-care.firebasestorage.app',
  );
}
